shmelegram/views/auth.py
from functools import wraps

from flask import (
    Blueprint, flash, redirect, render_template, request, 
    session, url_for, g
)

from shmelegram.models import User
from shmelegram import db, utils


def logged_in(func):
    @wraps(func)
    def inner(*args, **kwargs):
        if not session.get('user_id'):
            return redirect(url_for('auth.login', next=request.endpoint))
        return func(*args, **kwargs)
    return inner


bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        if not utils.validate_username(username):
            error = "Invalid username"
        elif not utils.validate_password(password):
            error = "Invalid password"
        elif db.session.query(User.id).filter_by(
                username=username).first() is not None:
            error = "User with this username alraedy exists."
        if not error:
            try:
                user = User(username=username, password=password)
                db.session.add(user)
            except Exception:
                error = 'Unexpected error occurred, try again later'
            else:
                flash('User successfully created', 'success')
                return redirect(url_for('auth.login'))
        flash(error, 'error')
    return render_template('auth/register.html', form=request.form)


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        error = None
        if not username:
            error = "Invalid username"
        elif not password:
            error = "Invalid password"
        elif db.session.query(User.id).filter_by(
                username=username).first() is None:
            error = "No user with such username exists"
        if not error:
            user = User.query.filter_by(username=username).first()
            if user.check_password(password):
                session['user_id'] = user.id
                return redirect(url_for('home.index'))
            error = "Passwords do not match"
        flash(error, 'error')
    return render_template('auth/login.html', form=request.form)


@bp.before_app_request
def load_user():
    user_id = session.get("user_id") 
    if user_id:
        g.user = User.query.get(user_id)

shmelegram/views/chat.py
from flask import render_template, session, Blueprint

from shmelegram.views.auth import logged_in


bp = Blueprint('chat', __name__, url_prefix='/')


@bp.route('', methods=('GET', ))
@logged_in
def index():
    return render_template('chat.html', user_id=session.get('user_id'))

shmelegram/views/home.py
from flask import render_template, Blueprint


bp = Blueprint('home', __name__, url_prefix='/home')


@bp.route('/', methods=('GET', ))
def index():
    return render_template('home/index.html', active_page='home')


@bp.route('/about', methods=('GET', ))
def about():
    return render_template('home/about.html', active_page='about')

shmelegram/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
	<title>Shmelegram{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
	{% block styles %}{% endblock %}
</head>
<body>
	{% block body %}{% endblock %}
	<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='js/socket.io.min.js') }}"></script>
	{% block js %}{% endblock %}
</body>
</html>

shmelegram/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand nav-link" href="{{ url_for('home.index') }}">
    <img 
      src="{{ url_for('static', filename='images/logo-nobg.png') }}" 
      height="60px" alt="Shmelegram logo"
    >
    <span class=".d-none .d-sm-block .d-sm-none .d-md-block">Shmelegram</span>
  </a>
  <button 
    class="navbar-toggler" type="button" data-bs-toggle="collapse" 
    data-bs-target="#navContent" aria-controls="navContent" aria-expanded="false" 
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navContent">
    <div class="navbar-nav">
      <a 
        class="nav-link {% if active_page == 'home' %}active{% endif %}" 
        aria-current="page" href="{{ url_for('home.index') }}"
      >
        Home
      </a>
      <a class="nav-link" href="{{ url_for('chat.index') }}">Chat</a>
      <a 
        class="nav-link {% if active_page == 'about' %}active{% endif %}" 
        href="{{ url_for('home.about') }}"
      >
        About
      </a> 
      <div class="nav-item dropdown">
        <a 
          class="nav-link {% if active_page == 'auth' %}active{% endif %} dropdown-toggle" 
          href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" 
          aria-haspopup="true" aria-expanded="false"
        >
          Authentication
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{{ url_for('auth.login') }}">Log in</a>
          <a class="dropdown-item" href="{{ url_for('auth.register') }}">Register</a>
        </div>
      </div>
    </div>
  </div>
</nav>